config/routes.rb
Rails.application.routes.draw do
  resources :labels
  get "/admin/users", to: 'admin/users#index', as: :admin_users_path_index
  namespace :admin do
    resources :users
  end
  
  get '/', to: 'tasks#index'
  resources :tasks

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  
  has_secure_password
  validates :password, length: { minimum: 6 }

  
  before_destroy :destroy_action
  before_update :update_action
 
  has_many :tasks, dependent: :destroy

  private
  def destroy_action
    if User.where(admin:true).count == 1 && self.admin
      throw :abort
    end
  end

  def update_action
    @admin_users = User.where(admin: true)
      if(@admin_users.count == 1 && @admin_users.first == self) && self.admin == false
        throw.abort
      end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :destroy, :update]
  before_action :require_admin

  def new
    # binding.pry
    @user = User.new
   
  end

  def create
    # binding.pry
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def edit
    @tasks = @user.tasks.all
    @tasks = @tasks.page(params[:page]).per(5)
  end

  def update
    if @user.update(user_params)
      flash[:notice] =  "ユーザー #{@user.name} 更新しました"
      redirect_to admin_users_path
    else
      render :edit, notice: "管理者がいなくなります！ #{@user.name} の管理者を外して更新ができません！"
    end
  end

  def show
    # binding.irb
    # 下のコマンドだとuser paramが空というエラーでる。多分taskを指定してなかったからかも
    # @user = User.find(user_params[:id])
    @tasks = @user.tasks.all
    @tasks = @tasks.page(params[:page]).per(5)
  end

  def index
    @users = User.all.includes(:tasks)
  end

  def destroy
    if@user.destroy
      redirect_to admin_users_path, notice: "ユーザー #{@user.name} を削除しました"
    else
      redirect_to admin_users_path, notice: "管理者がいなくなります！ #{@user.name} を削除できません！"
    end
  end
 
  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password)  
  end

  def require_admin
    unless current_user.admin?
      redirect_to tasks_path, notice: "あなたは管理者ではありません"
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    redirect_to user_path(current_user.id) if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = '登録しました'
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks
    unless @user == current_user
      redirect_to tasks_path, notice: '他人のページへアクセスはできません'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h2>ユーザー編集</h2>
  <%= form_with(model:[:admin,@user], loclal: true) do |form| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%@user%> from being saved:</h2>
          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :名前 %>
        <%= form.text_field :name %>
      </div>

      <div class="field">
        <%= form.label :管理者権限 %>
        <%= form.check_box :adimin %>
      </div>

      <div class="field">
        <%= form.label :メールアドレス %>
        <%= form.email_field :email %>
      </div>

      <div class="field">
        <%= form.label :パスワード %>
        <%= form.password_field :password %>
      </div>

        <%= form.submit "更新",class: "btn btn-primary" %>
    <% end %>
<%= link_to 'ユーザー一覧', new_admin_user_path%>

app/views/admin/users/index.html.erb
<h2>ユーザー登録一覧</h2>

<table class="table">
<br>
  <thead>
    <tr class="table-info">
      <th><%= t('user.id') %></th>
      <th><%= t('user.name') %></th>
      <th><%= t('user.admin') %></th>
      <th><%= t('user.task_count') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.admin %></td>
          <td><%= user.tasks.count %></td>
          <td><%= link_to 'Show', admin_user_path(user) %></td>
          <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
          <td><%= link_to 'Delete', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>  
</table>
<br>
<br>
<%= button_to '新規ユーザー作成', new_admin_user_path, method: :get, class: "btn btn-primary" %>

app/views/admin/users/new.html.erb
<h1>管理ユーザー用 新規ユーザー登録</h1>
<%=form_with(model: [:admin, @user],local: true) do |form|%>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%@user%> from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :ユーザー名 %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :管理者権限 %>
      <%= form.check_box :admin %>
    </div>

    <div class="field">
      <%= form.label :メールアドレス %>
      <%= form.email_field :email %>
    </div>

    <div class="field">
      <%= form.label :パスワード %>
      <%= form.password_field :password %>
    </div>

    <div class="actions">
      <%= form.submit "登録" %>
    </div>
  <% end %>

app/views/admin/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>

<table>
  <thead>
    <tr>
      <th>タスク</th>
      <th>詳細</th>
      <th>期限</th>
      <th>ステータス</th>
      <th>優先度</th>
      <th>閲覧</th>
      <th>編集</th>
      <th>削除</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.tasks.each do |task| %>
      <tr>
        <td class = "task_list" ><%= task.name %></td>
        <td><%= task.content %></td>
        <td><%= task.deadline %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Deliete', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>